name: Another Try

on:
  push:
    branches: [ main ]

jobs:
  firstjob:
      runs-on: ubuntu-latest

      steps:
        - name: Greetings
          run: echo "This has to work this time"
          run: 
  echo "Hello Ritish"
  echo "This is my first GitHub Action"
  uname -a

